### ISSUE TITLE
Multi-objective Genetic Algorithm Optimization of Water Supply Systems

### ISSUE THREAD

**Issue by rogersisci** [openseattle/convictionvacation#15]
hello Stephen Chan, In the project "Multi-objective Genetic Algorithm Optimization of Water Supply Systems " the files:

EPANETInputLocation = "c:\\EPATEST\\robmanualnetwork.inp";
pipeDatabaseInputLocation = "c:\\EPATEST\\robtestpipedatabase.txt";

Could you provide us with the structure of those files? Thank you for your great contribution.

**Comment by sscchan** [comment]
Wrong project for issue. Closing.
