### ISSUE TITLE
Make calculator results mobile friendly

### ISSUE THREAD

**Issue by evamaxfield** [openseattle/convictionvacation#18]
**Description:**
When testing the master branch I tried the entire process with a squashed window and the results form has the same behavior as before #13 where the table doesn't retain useful context as to which text belongs to which columns.

![image](https://user-images.githubusercontent.com/17132317/66981304-29cbd500-f068-11e9-9ace-d2d2d36c5d8b.png)

**Expected Behavior:**
The results form should have the same behavior as the entry form where when the table is squashed, the column names follow the text.

**System and Software:**
* Browser: multiple
* Exact URL: no route switch

 **Additional context**
n/a

**Comment by evamaxfield** [comment]
@tohuynh can I assign this to you since you handled #13 ?

**Comment by tohuynh** [comment]
> @tohuynh can I assign this to you since you handled #13 ?

Yes, I will take a look.
