### ISSUE TITLE
Fix website auto-deployment

### ISSUE THREAD

**Issue by evamaxfield** [openseattle/convictionvacation#28]
For some reason `gh-pages` is failing to deploy properly when using the GitHub actions workflow but correctly deploys using `npm run deploy`.

I think this is being caused by the git history being purged each time it runs as simply running `npm run deploy` adds a commit instead of removing the entire history. For now, website deployments will be manual after a series of commits / PRs.

**Comment by evamaxfield** [comment]
For tracking purposes: my team at work found the bug. `gh-pages` really doesn't like it when you clear the git history of the `gh-pages` branch. So we are working on a better deployment system with github actions.

**Comment by sscchan** [comment]
Github actions are actually implemented. Resolving this issue.
