### ISSUE TITLE
Need instruction for setting up Docker image based development environment.

### ISSUE THREAD

**Issue by sscchan** [openseattle/convictionvacation#35]
This project has volunteers that uses a number of different OSs.

With certain OSes (e.g. Windows, old LTR of CentOS, etc) will encounter severe friction when new volunteers are attempting to set up the development environment.

We should investigate and document steps (especially for Windows) on how to use dockerized development environment to expedite setting up of development environments. 

We need to make sure our instructions covers how a user can run test (e.g. npm test) within the docker container and access the local server that serves the static pages.

We should aim to make dev environment setup as pain free as possible for hackathon scenarios. 

We have a docker hub organization account that can be used: https://hub.docker.com/orgs/openseattle

**Comment by GuessWhoSamFoo** [comment]
Closed #46
